// GENERATED by scripts/generate-pa-pseudocode.mjs -- do not edit.
//
// Server-only. ATTEMPT_CAPS and ATTEMPT_KINDS are read by functions/api/attempt-reveal.ts,
// quiz-reveal.ts, lesson-state and lesson-submissions; PA_PSEUDOCODE is the
// answer text and is handed out only by attempt-reveal, only to a student with
// every try spent. Bundled into the Pages Function worker at deploy and NEVER a
// static asset. Do not import this from app/ or components/: the browser must
// never receive it (scripts/check-ai-grader-leak.mjs probes public/ and out/).

export const ATTEMPT_CAPS: Record<string, number> = {
  "2-7-2-ch2-individual-pa-own-words": 3,
  "2-7-5-ch2-individual-pa-write-the-steps": 3
};

export const ATTEMPT_KINDS: Record<string, 'quiz' | 'ai' | 'client'> = {
  "2-7-2-ch2-individual-pa-own-words": "ai",
  "2-7-5-ch2-individual-pa-write-the-steps": "ai"
};

export const PA_PSEUDOCODE: Record<string, string> = {};
