// GENERATED by scripts/generate-quiz-keys.mjs from lessons/*/lesson.json -- do not edit.
//
// The summative quiz answer key, read server-side by functions/api/quiz-reveal.ts.
// Bundled into the Pages Function worker at deploy; NEVER served as a static
// asset (a public/ file is fetchable by anyone, which is the exact leak
// lib/quiz-redact.ts prevents). Do not import this from anything under app/
// or components/ -- the browser must never receive this module.
// Regenerated by prebuild; rerun manually after editing a summative lesson.

export interface QuizKeyQuestion {
  id: string;
  /** Index into the question's authored options array, never the drawn order. */
  answer: number;
  optionText: string;
  explanation: string;
  variant?: string;
}

export interface QuizKey {
  variants?: string[];
  questions: QuizKeyQuestion[];
}

export const QUIZ_KEYS: Record<string, QuizKey> = {
    "2-7-1-ch2-individual-pa-concepts": {
      "variants": [
        "a",
        "b",
        "c"
      ],
      "questions": [
        {
          "id": "c1-if-decides",
          "answer": 0,
          "optionText": "It converts it to true or false, using the six falsy values",
          "explanation": "if converts whatever is inside the parentheses to a boolean (2.1.12). Zero, an empty string, null, undefined, NaN and false convert to false; everything else converts to true. That is why if (x == true) is redundant when x is already a boolean -- if (x) does the same job."
        },
        {
          "id": "c2-switch-equality",
          "answer": 0,
          "optionText": "With strict equality (===), so a string \"4\" never matches the number 4",
          "explanation": "switch matches with strict equality (2.3.18). switch (4) never matches case \"4\": the number 4 and the text \"4\" are different values under ===, which is exactly why a value of the wrong type falls through to default."
        },
        {
          "id": "c3-loop-shapes",
          "answer": 1,
          "optionText": "6",
          "explanation": "Every pass of the outer loop runs the inner loop start to finish, so the inner body runs 3 x 2 = 6 times (2.4.24). Nested-loop cost is the product, not the sum."
        },
        {
          "id": "a-t1-equality",
          "answer": 0,
          "optionText": "empty",
          "explanation": "Loose equality converts before comparing: false becomes the number 0, and 0 == 0 is true, so the if runs and prints empty. That is the == trap; === would compare the boolean against the number and say false.",
          "variant": "a"
        },
        {
          "id": "a-t2-step",
          "answer": 0,
          "optionText": "2 4 6 8 10 (five lines)",
          "explanation": "The step is += 2, so i goes 2, 4, 6, 8, 10 and stops before 12. The step clause of the for header runs at the end of every pass, and here it adds two each time.",
          "variant": "a"
        },
        {
          "id": "a-t3-fallthrough",
          "answer": 1,
          "optionText": "Intermediate then Advanced",
          "explanation": "Case 2 matches and prints Intermediate, but its case has no break, so execution falls through into case 3 and prints Advanced too. Then case 3's break stops it. Two lines, in that order.",
          "variant": "a"
        },
        {
          "id": "a-t4-nested",
          "answer": 0,
          "optionText": "1-1, 1-2, 2-1, 2-2, 3-1, 3-2 — six lines",
          "explanation": "The outer loop runs three passes. Each pass runs the inner loop start to finish: col is 1 then 2 while row stays put. So the pairs come out 1-1, 1-2, then 2-1, 2-2, then 3-1, 3-2.",
          "variant": "a"
        },
        {
          "id": "a-t5-finally",
          "answer": 0,
          "optionText": "A, B boom, C, D",
          "explanation": "A prints, the throw stops the try block, the catch prints B with the message, finally runs either way and prints C, and then the line after the whole statement prints D. finally is for cleanup that runs either way (2.5.21).",
          "variant": "a"
        },
        {
          "id": "b-t1-equality",
          "answer": 1,
          "optionText": "empty",
          "explanation": "Loose equality converts false to the number 0, and 0 == 0 is true, so the if runs and prints empty. Under === the boolean and the number are different types and the comparison is false.",
          "variant": "b"
        },
        {
          "id": "b-t2-step",
          "answer": 0,
          "optionText": "3 6 9 12 (four lines)",
          "explanation": "The step is += 3, so i goes 3, 6, 9, 12 and stops before 15. Four lines.",
          "variant": "b"
        },
        {
          "id": "b-t3-fallthrough",
          "answer": 0,
          "optionText": "Weekend, then Sleep in",
          "explanation": "Case Sat matches and prints Weekend, but has no break, so it falls through into case Sun and prints Sleep in before Sun's break stops it.",
          "variant": "b"
        },
        {
          "id": "b-t4-nested",
          "answer": 0,
          "optionText": "1x1, 1x2, 1x3, 2x1, 2x2, 2x3 — six lines",
          "explanation": "The outer loop runs two passes; each pass runs the inner loop three times. Same six lines as any 2 x 3 nesting: the outer value holds while the inner sweeps.",
          "variant": "b"
        },
        {
          "id": "b-t5-finally",
          "answer": 0,
          "optionText": "W, X disk, Y, Z",
          "explanation": "Same trip as every form: try prints W, the throw hands control to catch which prints X with the message, finally prints Y either way, and the line after prints Z.",
          "variant": "b"
        },
        {
          "id": "c-t1-equality",
          "answer": 0,
          "optionText": "none",
          "explanation": "false converts to the number 0, and 0 == 0 is true, so the if runs. A const declared with 0 is still a number, and 0 == false is the loose-equality trap.",
          "variant": "c"
        },
        {
          "id": "c-t2-step",
          "answer": 0,
          "optionText": "5 10 15 20 (four lines)",
          "explanation": "The step is += 5, so i goes 5, 10, 15, 20 and stops before 25. Four lines.",
          "variant": "c"
        },
        {
          "id": "c-t3-fallthrough",
          "answer": 0,
          "optionText": "Small, then Medium",
          "explanation": "Case 1 matches and prints Small, then falls through into case 2 (no break on case 1) and prints Medium before case 2's break stops it. Default never runs.",
          "variant": "c"
        },
        {
          "id": "c-t4-nested",
          "answer": 0,
          "optionText": "1, 2, 2, 4, 3, 6 — six lines",
          "explanation": "Same trip as the other forms: outer 3 passes, inner 2 passes, six prints. The body computes i * j, so the values differ from form a, but the trip — one inner sweep per outer pass — is identical.",
          "variant": "c"
        },
        {
          "id": "c-t5-finally",
          "answer": 0,
          "optionText": "P, Q late, R, S",
          "explanation": "P prints, the throw jumps to catch, Q prints with the message, finally prints R whether or not there was an error, and the line after the statement prints S.",
          "variant": "c"
        }
      ]
    }
 
}
