flowchart TD
  A([Start])
  B[Set cheapCount to 0]
  C{{i = 0 to prices.length - 1}}
  D{Is prices at i under 10?}
  E[Add one to cheapCount]
  F[/Print Items under 10 and cheapCount/]
  Z([End])
  A --> B
  B --> C
  C -- "next item" --> D
  D -- "yes" --> E
  D -- "no" --> C
  E --> C
  C -- "done" --> F
  F --> Z
