flowchart TD
  A([Start])
  B[sum = 0]
  C{{for i from 0 to numbers.length - 1}}
  D{is there another number?}
  E[sum = sum + numbers i]
  F[/return sum/]
  Z([End])
  A --> B
  B --> C
  C --> D
  D -->|yes| E
  E --> C
  D -->|no| F
  F --> Z
